# Generated by Django 3.0.7 on 2021-09-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_smoothies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='smoothies',
            new_name='smoothie',
        ),
    ]
