# Generated by Django 3.0.7 on 2021-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_receipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='desc',
        ),
        migrations.AddField(
            model_name='receipe',
            name='desc1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='desc2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='desc3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='ingre',
            field=models.TextField(null=True),
        ),
    ]
