# Generated by Django 3.0.7 on 2021-09-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210911_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
